name: Decision

on:
  push:
    branches:
      - dev
      - master
      - prod

jobs:
  decide:
    runs-on: ubuntu-latest

    steps:
      - name: Determine Branch
        id: branch
        run: echo "::set-output name=branch::${GITHUB_REF##*/}"

      - name: Decide Workflow
        id: decide
        run: |
          if [[ "${{ steps.branch.outputs.branch }}" == "master" ]]; then
            echo "Running Master Workflow"
            echo "master.yml" >> $GITHUB_ENV
          elif [[ "${{ steps.branch.outputs.branch }}" == "prod" ]]; then
            echo "Running Production Workflow"
            echo "prod.yml" >> $GITHUB_ENV
          elif [[ "${{ steps.branch.outputs.branch }}" == "dev" ]]; then
            echo "Running Dev Workflow"
            echo "dev.yml" >> $GITHUB_ENV
          else
            echo "No Workflow Found for Branch"
            exit 1
          fi

      - name: Run Relevant Workflow
        run: |
          workflow_file="${{ env.GITHUB_WORKSPACE }}/.github/workflows/${{ steps.decide.outputs.workflow }}"
          echo "Using Workflow File: $workflow_file"
          chmod +x $workflow_file
          $workflow_file
