name: Decision

on:
  push:
    branches:
      - '*'

jobs:
  decide:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o ~/githubcli-archive-keyring.gpg
          echo "deb [signed-by=~/githubcli-archive-keyring.gpg arch=all] https://cli.github.com/packages stable main" | tee ~/github-cli.list
          sudo mv ~/github-cli.list /etc/apt/sources.list.d/github-cli.list
          sudo apt update
          sudo apt install -y gh

      - name: Determine Branch
        id: branch
        run: echo "::set-output name=branch::${GITHUB_REF##*/}"

      - name: Decide Workflow
        id: decide
        run: |
          if [[ ${{ steps.branch.outputs.branch }} == "master" ]]; then
            echo "Running Master Workflow"
            echo "::set-output name=workflow::master.yml"
          elif [[ ${{ steps.branch.outputs.branch }} == "production" ]]; then
            echo "Running Production Workflow"
            echo "::set-output name=workflow::prod.yml"
          elif [[ ${{ steps.branch.outputs.branch }} == "dev" ]]; then
            echo "Running Dev Workflow"
            echo "::set-output name=workflow::dev.yml"
          else
            echo "No Workflow Found for Branch"
            exit 1
          fi

      - name: Trigger Relevant Workflow
        uses: actions/checkout@v2

      - name: Run Relevant Workflow
        run: |
          workflow_file=".github/workflows/${{ steps.decide.outputs.workflow }}"
          echo "Using Workflow File: $workflow_file"
          echo "::set-env name=WORKFLOW_FILE::$workflow_file"

      - name: Execute Workflow
        run: |
          workflow_file=$WORKFLOW_FILE
          echo "Running Workflow: $workflow_file"
          gh workflow run "$workflow_file" --ref "${{ github.ref }}" --env "WORKFLOW_FILE=$workflow_file"
