name: Decision

on:
  push:
    branches:
      - '*'

jobs:
  decide:
    runs-on: ubuntu-latest

    steps:
      - name: Determine Branch
        id: branch
        run: echo "::set-output name=branch::${GITHUB_REF##*/}"

      - name: Decide Workflow
        id: decide
        run: |
          if [[ ${{ steps.branch.outputs.branch }} == "master" ]]; then
            echo "Running Master Workflow"
            echo "::set-output name=workflow::master.yml"
          elif [[ ${{ steps.branch.outputs.branch }} == "production" ]]; then
            echo "Running Production Workflow"
            echo "::set-output name=workflow::prod.yml"
          elif [[ ${{ steps.branch.outputs.branch }} == "dev" ]]; then
            echo "Running Dev Workflow"
            echo "::set-output name=workflow::dev.yml"
          else
            echo "No Workflow Found for Branch"
            exit 1
          fi

      - name: Set Workflow File
        id: set_workflow_file
        run: echo "::set-output name=workflow_file::.github/workflows/${{ steps.decide.outputs.workflow }}"

      - name: Grant Execute Permission to Detected Branch Workflow
        run: chmod +x "${{ steps.set_workflow_file.outputs.workflow_file }}"

      - name: Run Relevant Workflow
        uses: actions/checkout@v2

      - name: Execute Relevant Workflow
        run: |
          workflow_file="${{ steps.set_workflow_file.outputs.workflow_file }}"
          echo "Using Workflow File: $workflow_file"
          ./${workflow_file}
