name: Deploy To Dev Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Capistrano Deploy to Server
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Set WORKFLOW_FILE environment variable
        run: echo "WORKFLOW_FILE=.github/workflows/dev.yml" >> $GITHUB_ENV

      - name: Set SECRET_TEST_USER environment variable
        env:
          SECRET_DEV_USER: ${{ secrets.DEV_USER }}
        run: echo "DEV_USER=${{ env.SECRET_DEV_USER }}"
        
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Debug
        run: |
          echo "DEBUG: WORKFLOW_FILE is set to $WORKFLOW_FILE"
