name: DevOps Metrics

on:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: |
        npm run build
        echo "Build completed."

    - name: Run Tests
      run: |
        npm test
        echo "Tests completed."

    - name: Emit Metrics
      run: |
        # Calculate build duration in seconds
        BUILD_START=$(date -u +%s)
        npm run build
        BUILD_SUCCESS=$?
        BUILD_END=$(date -u +%s)
        BUILD_DURATION=$((BUILD_END - BUILD_START))

        echo "Build Duration (seconds): $BUILD_DURATION"
        echo "Build Success: $BUILD_SUCCESS"

        # Emit metrics in Prometheus format
        echo "build_duration_seconds $BUILD_DURATION" > metrics.txt
        echo "build_success_status $BUILD_SUCCESS" >> metrics.txt

        # Set up a simple web server to expose metrics
        python -m http.server 8000 --bind 0.0.0.0 &
