jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install prometheus_client

      - name: Run tests
        run: |
          # Your test commands here

      - name: Generate Prometheus Metrics
        run: |
          from prometheus_client import CollectorRegistry, Gauge, push_to_gateway, pushadd_to_gateway
          
          # Your code logic here
          
          # Create a Prometheus gauge metric
          gauge = Gauge('github_actions_workflow_status', 'Workflow status', ['status'])
          
          # Set the metric value based on your logic
          if success:
              gauge.labels(status='success').set(1)
          else:
              gauge.labels(status='failed').set(1)
          
          # Push the metric to the Prometheus Pushgateway
          registry = CollectorRegistry()
          pushadd_to_gateway('3.84.90.146:9091', job='github-actions', registry=registry)
