name: Send Prometheus notification on RSpec outcome

on:
  push:
    branches:
      - master

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check RSpec status
        run: |
          if [ $? -eq 0 ]; then
            echo "success"
          else
            echo "failed"
          fi

      - name: Create notification file
        run: |
          echo "success_count=1" > notification.txt
          if [ "$status" == "failed" ]; then
            echo "failed_count=1" >> notification.txt
          fi

      - name: Send Prometheus notification
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"data": {"success_count": 1, "failed_count": 0}}' http://3.84.90.146:9090/metrics
